-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 14:40:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema call24
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema call24
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `call24` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `call24` ;

-- -----------------------------------------------------
-- Table `call24`.`nicknames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`nicknames` (
  `idnicknames` INT NOT NULL AUTO_INCREMENT,
  `Nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnicknames`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`passwords` (
  `idpasswords` INT NOT NULL AUTO_INCREMENT,
  `Pass` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idpasswords`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `call24`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`emails` (
  `idemails` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idemails`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`admins` (
  `idadmins` INT NOT NULL AUTO_INCREMENT,
  `nicknames_idnicknames` INT NOT NULL,
  `passwords_idpasswords` INT NOT NULL,
  `emails_idemails` INT NOT NULL,
  PRIMARY KEY (`idadmins`, `nicknames_idnicknames`, `passwords_idpasswords`, `emails_idemails`),
  INDEX `fk_admins_nicknames1_idx` (`nicknames_idnicknames` ASC) VISIBLE,
  INDEX `fk_admins_passwords1_idx` (`passwords_idpasswords` ASC) VISIBLE,
  INDEX `fk_admins_emails1_idx` (`emails_idemails` ASC) VISIBLE,
  CONSTRAINT `fk_admins_nicknames1`
    FOREIGN KEY (`nicknames_idnicknames`)
    REFERENCES `call24`.`nicknames` (`idnicknames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admins_passwords1`
    FOREIGN KEY (`passwords_idpasswords`)
    REFERENCES `call24`.`passwords` (`idpasswords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admins_emails1`
    FOREIGN KEY (`emails_idemails`)
    REFERENCES `call24`.`emails` (`idemails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`savedcalls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`savedcalls` (
  `idsavedcalls` INT NOT NULL,
  `savedcall` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idsavedcalls`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `call24`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`calls` (
  `idcalls` INT NOT NULL AUTO_INCREMENT,
  `Lenght` TIME NOT NULL,
  `savedcalls_idsavedcalls` INT NOT NULL,
  PRIMARY KEY (`idcalls`, `savedcalls_idsavedcalls`),
  INDEX `fk_calls_savedcalls1_idx` (`savedcalls_idsavedcalls` ASC) VISIBLE,
  CONSTRAINT `fk_calls_savedcalls1`
    FOREIGN KEY (`savedcalls_idsavedcalls`)
    REFERENCES `call24`.`savedcalls` (`idsavedcalls`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`name` (
  `idname` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `call24`.`surname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`surname` (
  `idsurname` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsurname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `call24`.`phonebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`phonebook` (
  `idphonebook` INT NOT NULL AUTO_INCREMENT,
  `Number` INT NOT NULL,
  PRIMARY KEY (`idphonebook`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`employees` (
  `idemployees` INT NOT NULL AUTO_INCREMENT,
  `name_idname` INT NOT NULL,
  `surname_idsurname` INT NOT NULL,
  `nicknames_idnicknames` INT NOT NULL,
  `emails_idemails` INT NOT NULL,
  `passwords_idpasswords` INT NOT NULL,
  `phonebook_idphonebook` INT NOT NULL,
  PRIMARY KEY (`idemployees`, `name_idname`, `surname_idsurname`, `nicknames_idnicknames`, `emails_idemails`, `passwords_idpasswords`, `phonebook_idphonebook`),
  INDEX `fk_employees_name1_idx` (`name_idname` ASC) VISIBLE,
  INDEX `fk_employees_surname1_idx` (`surname_idsurname` ASC) VISIBLE,
  INDEX `fk_employees_nicknames1_idx` (`nicknames_idnicknames` ASC) VISIBLE,
  INDEX `fk_employees_emails1_idx` (`emails_idemails` ASC) VISIBLE,
  INDEX `fk_employees_passwords1_idx` (`passwords_idpasswords` ASC) VISIBLE,
  INDEX `fk_employees_phonebook1_idx` (`phonebook_idphonebook` ASC) VISIBLE,
  CONSTRAINT `fk_employees_name1`
    FOREIGN KEY (`name_idname`)
    REFERENCES `call24`.`name` (`idname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_surname1`
    FOREIGN KEY (`surname_idsurname`)
    REFERENCES `call24`.`surname` (`idsurname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_nicknames1`
    FOREIGN KEY (`nicknames_idnicknames`)
    REFERENCES `call24`.`nicknames` (`idnicknames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_emails1`
    FOREIGN KEY (`emails_idemails`)
    REFERENCES `call24`.`emails` (`idemails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_passwords1`
    FOREIGN KEY (`passwords_idpasswords`)
    REFERENCES `call24`.`passwords` (`idpasswords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_phonebook1`
    FOREIGN KEY (`phonebook_idphonebook`)
    REFERENCES `call24`.`phonebook` (`idphonebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`managers` (
  `idmanagers` INT NOT NULL AUTO_INCREMENT,
  `name_idname` INT NOT NULL,
  `surname_idsurname` INT NOT NULL,
  `nicknames_idnicknames` INT NOT NULL,
  `phonebook_idphonebook` INT NOT NULL,
  `emails_idemails` INT NOT NULL,
  `passwords_idpasswords` INT NOT NULL,
  PRIMARY KEY (`idmanagers`, `name_idname`, `surname_idsurname`, `nicknames_idnicknames`, `phonebook_idphonebook`, `emails_idemails`, `passwords_idpasswords`),
  INDEX `fk_managers_name1_idx` (`name_idname` ASC) VISIBLE,
  INDEX `fk_managers_surname1_idx` (`surname_idsurname` ASC) VISIBLE,
  INDEX `fk_managers_nicknames1_idx` (`nicknames_idnicknames` ASC) VISIBLE,
  INDEX `fk_managers_phonebook1_idx` (`phonebook_idphonebook` ASC) VISIBLE,
  INDEX `fk_managers_emails1_idx` (`emails_idemails` ASC) VISIBLE,
  INDEX `fk_managers_passwords1_idx` (`passwords_idpasswords` ASC) VISIBLE,
  CONSTRAINT `fk_managers_name1`
    FOREIGN KEY (`name_idname`)
    REFERENCES `call24`.`name` (`idname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_surname1`
    FOREIGN KEY (`surname_idsurname`)
    REFERENCES `call24`.`surname` (`idsurname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_nicknames1`
    FOREIGN KEY (`nicknames_idnicknames`)
    REFERENCES `call24`.`nicknames` (`idnicknames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_phonebook1`
    FOREIGN KEY (`phonebook_idphonebook`)
    REFERENCES `call24`.`phonebook` (`idphonebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_emails1`
    FOREIGN KEY (`emails_idemails`)
    REFERENCES `call24`.`emails` (`idemails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_passwords1`
    FOREIGN KEY (`passwords_idpasswords`)
    REFERENCES `call24`.`passwords` (`idpasswords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `name_idname` INT NOT NULL,
  `surname_idsurname` INT NOT NULL,
  `emails_idemails` INT NOT NULL,
  `phonebook_idphonebook` INT NOT NULL,
  `calls_idcalls` INT NOT NULL,
  `calls_savedcalls_idsavedcalls` INT NOT NULL,
  `employees_idemployees` INT NULL,
  `managers_idmanagers` INT NULL,
  PRIMARY KEY (`idclients`, `name_idname`, `surname_idsurname`, `emails_idemails`, `phonebook_idphonebook`, `calls_savedcalls_idsavedcalls`, `calls_idcalls`),
  INDEX `fk_clients_name1_idx` (`name_idname` ASC) VISIBLE,
  INDEX `fk_clients_surname1_idx` (`surname_idsurname` ASC) VISIBLE,
  INDEX `fk_clients_emails1_idx` (`emails_idemails` ASC) VISIBLE,
  INDEX `fk_clients_phonebook1_idx` (`phonebook_idphonebook` ASC) VISIBLE,
  INDEX `fk_clients_calls1_idx` (`calls_idcalls` ASC, `calls_savedcalls_idsavedcalls` ASC) VISIBLE,
  INDEX `fk_clients_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  INDEX `fk_clients_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  CONSTRAINT `fk_clients_name1`
    FOREIGN KEY (`name_idname`)
    REFERENCES `call24`.`name` (`idname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_surname1`
    FOREIGN KEY (`surname_idsurname`)
    REFERENCES `call24`.`surname` (`idsurname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_emails1`
    FOREIGN KEY (`emails_idemails`)
    REFERENCES `call24`.`emails` (`idemails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_phonebook1`
    FOREIGN KEY (`phonebook_idphonebook`)
    REFERENCES `call24`.`phonebook` (`idphonebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_calls1`
    FOREIGN KEY (`calls_idcalls` , `calls_savedcalls_idsavedcalls`)
    REFERENCES `call24`.`calls` (`idcalls` , `savedcalls_idsavedcalls`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`managers_has_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`managers_has_employees` (
  `managers_idmanagers` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`managers_idmanagers`, `employees_idemployees`),
  INDEX `fk_managers_has_employees_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  INDEX `fk_managers_has_employees_managers_idx` (`managers_idmanagers` ASC) VISIBLE,
  CONSTRAINT `fk_managers_has_employees_managers`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_managers_has_employees_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
