-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 14:55:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema call24
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema call24
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `call24` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `call24` ;

-- -----------------------------------------------------
-- Table `call24`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`admins` (
  `idadmins` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idadmins`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`employees` (
  `idemployees` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idemployees`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`managers` (
  `idmanagers` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idmanagers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `employees_idemployees` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  PRIMARY KEY (`idclients`, `employees_idemployees`, `managers_idmanagers`),
  INDEX `fk_clients_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  INDEX `fk_clients_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  CONSTRAINT `fk_clients_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`calls` (
  `idcalls` INT NOT NULL AUTO_INCREMENT,
  `Lenght` TIME NOT NULL,
  `clients_idclients` INT NOT NULL,
  `clients_employees_idemployees` INT NOT NULL,
  `clients_managers_idmanagers` INT NOT NULL,
  PRIMARY KEY (`idcalls`, `clients_idclients`, `clients_employees_idemployees`, `clients_managers_idmanagers`),
  INDEX `fk_calls_clients1_idx` (`clients_idclients` ASC, `clients_employees_idemployees` ASC, `clients_managers_idmanagers` ASC) VISIBLE,
  CONSTRAINT `fk_calls_clients1`
    FOREIGN KEY (`clients_idclients` , `clients_employees_idemployees` , `clients_managers_idmanagers`)
    REFERENCES `call24`.`clients` (`idclients` , `employees_idemployees` , `managers_idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`emails` (
  `idemails` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `admins_idadmins` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  `clients_idclients` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`idemails`, `admins_idadmins`, `managers_idmanagers`, `clients_idclients`, `employees_idemployees`),
  INDEX `fk_emails_admins1_idx` (`admins_idadmins` ASC) VISIBLE,
  INDEX `fk_emails_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  INDEX `fk_emails_clients1_idx` (`clients_idclients` ASC) VISIBLE,
  INDEX `fk_emails_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  CONSTRAINT `fk_emails_admins1`
    FOREIGN KEY (`admins_idadmins`)
    REFERENCES `call24`.`admins` (`idadmins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emails_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emails_clients1`
    FOREIGN KEY (`clients_idclients`)
    REFERENCES `call24`.`clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emails_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`nicknames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`nicknames` (
  `idnicknames` INT NOT NULL AUTO_INCREMENT,
  `Nickname` VARCHAR(45) NOT NULL,
  `admins_idadmins` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`idnicknames`, `admins_idadmins`, `managers_idmanagers`, `employees_idemployees`),
  INDEX `fk_nicknames_admins1_idx` (`admins_idadmins` ASC) VISIBLE,
  INDEX `fk_nicknames_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  INDEX `fk_nicknames_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  CONSTRAINT `fk_nicknames_admins1`
    FOREIGN KEY (`admins_idadmins`)
    REFERENCES `call24`.`admins` (`idadmins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nicknames_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nicknames_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`phonebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`phonebook` (
  `idphonebook` INT NOT NULL AUTO_INCREMENT,
  `Number` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`idphonebook`, `managers_idmanagers`, `employees_idemployees`),
  INDEX `fk_phonebook_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  INDEX `fk_phonebook_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  CONSTRAINT `fk_phonebook_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phonebook_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `call24`.`name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`name` (
  `idname` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `admins_idadmins` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  `clients_idclients` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`idname`, `admins_idadmins`, `managers_idmanagers`, `clients_idclients`, `employees_idemployees`),
  INDEX `fk_name_admins_idx` (`admins_idadmins` ASC) VISIBLE,
  INDEX `fk_name_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  INDEX `fk_name_clients1_idx` (`clients_idclients` ASC) VISIBLE,
  INDEX `fk_name_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  CONSTRAINT `fk_name_admins`
    FOREIGN KEY (`admins_idadmins`)
    REFERENCES `call24`.`admins` (`idadmins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_name_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_name_clients1`
    FOREIGN KEY (`clients_idclients`)
    REFERENCES `call24`.`clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_name_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `call24`.`surname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`surname` (
  `idsurname` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `admins_idadmins` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  `clients_idclients` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`idsurname`, `admins_idadmins`, `managers_idmanagers`, `clients_idclients`, `employees_idemployees`),
  INDEX `fk_surname_admins1_idx` (`admins_idadmins` ASC) VISIBLE,
  INDEX `fk_surname_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  INDEX `fk_surname_clients1_idx` (`clients_idclients` ASC) VISIBLE,
  INDEX `fk_surname_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  CONSTRAINT `fk_surname_admins1`
    FOREIGN KEY (`admins_idadmins`)
    REFERENCES `call24`.`admins` (`idadmins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surname_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surname_clients1`
    FOREIGN KEY (`clients_idclients`)
    REFERENCES `call24`.`clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surname_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `call24`.`passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`passwords` (
  `idpasswords` INT NOT NULL AUTO_INCREMENT,
  `Pass` VARCHAR(255) NOT NULL,
  `admins_idadmins` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  `employees_idemployees` INT NOT NULL,
  PRIMARY KEY (`idpasswords`, `admins_idadmins`, `managers_idmanagers`, `employees_idemployees`),
  INDEX `fk_passwords_admins1_idx` (`admins_idadmins` ASC) VISIBLE,
  INDEX `fk_passwords_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  INDEX `fk_passwords_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  CONSTRAINT `fk_passwords_admins1`
    FOREIGN KEY (`admins_idadmins`)
    REFERENCES `call24`.`admins` (`idadmins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passwords_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passwords_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `call24`.`employees_has_managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `call24`.`employees_has_managers` (
  `employees_idemployees` INT NOT NULL,
  `managers_idmanagers` INT NOT NULL,
  PRIMARY KEY (`employees_idemployees`, `managers_idmanagers`),
  INDEX `fk_employees_has_managers_managers1_idx` (`managers_idmanagers` ASC) VISIBLE,
  INDEX `fk_employees_has_managers_employees1_idx` (`employees_idemployees` ASC) VISIBLE,
  CONSTRAINT `fk_employees_has_managers_employees1`
    FOREIGN KEY (`employees_idemployees`)
    REFERENCES `call24`.`employees` (`idemployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_has_managers_managers1`
    FOREIGN KEY (`managers_idmanagers`)
    REFERENCES `call24`.`managers` (`idmanagers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
